FROM nginx:1.25.4-alpine

COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY docs/redoc.html /usr/share/nginx/redoc/redoc.html
COPY docs/openapi-schema.yml /usr/share/nginx/redoc/openapi-schema.yml
COPY frontend/build/ /usr/share/nginx/html/